# see https://github.com/bbatsov/rubocop#configuration
# for info on how to configure rubocop
# see https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# for default configuration

AllCops:
  TargetRubyVersion: 2.3

Rails:
  Enabled: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200
  # Enabled: false

Metrics/MethodLength:
  Max: 40
  # Enabled: false

Metrics/ModuleLength:
  Max: 500
  # Enabled: false

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 13

Style/RedundantReturn:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/IndentHash:
  EnforcedStyle: consistent

Metrics/ClassLength:
  Max: 200

Style/RedundantSelf:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/SingleLineBlockParams:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: false

Style/FrozenStringLiteralComment:
  Enabled: false
