# see https://github.com/bbatsov/rubocop#configuration
# for info on how to configure rubocop
# see https://github.com/bbatsov/rubocop/blob/master/config/default.yml
# for default configuration

require:
  - rubocop-thread_safety

AllCops:
  TargetRubyVersion: 2.4

Rails:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 200

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Max: 500

Metrics/AbcSize:
  Max: 50

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/PerceivedComplexity:
  Max: 13

Style/RedundantReturn:
  Enabled: false

Style/GuardClause:
  Enabled: false

Layout/IndentHash:
  EnforcedStyle: consistent

Metrics/ClassLength:
  Max: 200

Style/RedundantSelf:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/DefWithParentheses:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/SingleLineBlockParams:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

CaseIndentation:
  EnforcedStyle: end
  IndentOneStep: false

Style/FrozenStringLiteralComment:
  Enabled: false

ThreadSafety/NewThread:
  Exclude:
    - 'test/**/*'
