sudo: false
language: ruby
cache: bundler
bundler_args: --without debug
rvm:
- 2.4.1
addons:
  apt:
    packages:
      - redis-server
services:
- redis-server
env:
  global:
  - REDIS_HOST=localhost
  - REDIS_PORT=6379
  - REDIS_DB=0
  - CI_BUILD=1
notifications:
  email:
    on_success: change
    on_failure: change

# Lifecycle
before_install: gem install bundler
before_script: bundle exec rubocop -P -E -D
script: bundle exec rake test
