sudo: false
language: ruby
rvm:
- 2.4.1
before_install: gem install bundler -v 1.15.0
services:
- redis-server
env:
  global:
    - REDIS_HOST=localhost
    - REDIS_PORT=6379
    - REDIS_DB=0
    - CI_BUILD=1
  secure: "CrRYDwyb/JbFYUf556ohcVY6ehsVdQoXkfHMiJD2+gg2bm1eJKghQokuaBRI4k0qiu6PDdGVENrGJRJ2EacDYjxmbPei/8YZDioDfQ0U2ZKu8qSAsslmIZAYep9fVqS+VSF0gDzw1fQzUkcdZJm8mM/Meg2n+yQwk9hL1Mf1a/bzuWBgw8rPVHwyWHyy3r4vcdzbn6bdgKShp8+a+OfbHPMNeoXUf4BdAe3WEaqIKklFOuF/Scv5cSELCxg4TrRBzJJateGX/SLUEqhO7NSxiR+TZb2KmZ3HMVMmwT3aAbv+hAG0BqkX3ouE3HnpjQTs14JQRc3l3pS2yeqbzaZAg9ZiaiUJ1bxj3DpdYu384pWugoCydjv1SGswgOlJSnlybW2IlHmXDnLS3gTRQ7cop3oiCphb7bD1bQS2sZY9nd0CTQMWNYgM1ZrIgsm4cXplXEk3r3aqZbTUhz2BqMJQaMfgV49gnDUh5paFS3zQ9QK8E6IIZuhrTm/YX0fgFwAkTZNc1yrjbXkgemJYHWNH1NJ/3zB6v22MQh0UHMtP5iaUP4lfhko8w45zE8egSZUKxwSMDWBHuYaQUvCLBXzkF0V4EZHCkU4jfAdc17H+vINvy+7CltBynWepGl4fgUDPPSs6qi21zS+H+fjzXaAkgIZlmhpD07/PjptJgRa6qgE="
notifications:
  email:
    on_success: change
    on_failure: change
