version: '2'

networks:
  default:
    driver: bridge

services:
  lib:
    build: .
    stdin_open: true
    tty: true
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - ./:/var/lib/redstruct
  redis:
    image: redis:3.2-alpine
    expose:
      - "6379"
